CREATE SCHEMA Assessment
GO

CREATE TABLE Products (Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(15) UNIQUE, Price SMALLMONEY)

CREATE TABLE Customers (Id INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(15), LastName NVARCHAR(20),
	CardNumber BIGINT,
	CHECK ((CardNumber > 1000000000000000) AND 
		(CardNumber < 10000000000000000)))
GO

CREATE TABLE Orders (Id INT IDENTITY(1,1) PRIMARY KEY,
	ProductId INT CONSTRAINT ProductId_to_Product_FK
		REFERENCES Products (Id),
	CustomerId INT CONSTRAINT CustomerId_to_Customers_FK
		REFERENCES Customers (Id))
GO

--Add 3 records to all tables
--Product Data
SET IDENTITY_INSERT Products ON
INSERT INTO Products (Id, Name, Price)
	VALUES(1, 'Android', '250.50'), (2, 'Motorola', '0.99'),
	(3, 'Windows Phone', '0.01')
SET IDENTITY_INSERT Products OFF

--Customer Data
SET IDENTITY_INSERT Customers ON
INSERT INTO Customers (Id,FirstName,LastName,CardNumber)
	VALUES(1, 'Tom', 'Jones', 4346321466421356),
	(2, 'Sam', 'Minors', 40295039540392049),
	(3, 'Devin', 'Boone', 3949503950391924)
SET IDENTITY_INSERT Customers OFF

--Order Data
SET IDENTITY_INSERT Orders ON
INSERT INTO Orders (Id, ProductId, CustomerId)
	VALUES(1, 2, 3), (3,2,1), (2,3,1)
SET IDENTITY_INSERT Orders OFF
GO

--Add Iphone product priced at $200
INSERT Products (Name,Price) VALUES ('IPhone',200)
GO

--Add customer Tina Smith
INSERT Customers (FirstName,LastName) VALUES ('Tina','Smith')
GO

--Create order for Tina Smith bought Iphone
INSERT Orders(ProductId,CustomerId) 
	VALUES ((SELECT Id FROM Products WHERE Name = 'IPhone'),
		(SELECT Id FROM Customers WHERE FirstName = 'Tina'
		AND LastName = 'Smith'))
GO

--Report all orders by Tina Smith
SELECT * FROM Orders INNER JOIN Customers 
	ON Orders.CustomerId = Customers.Id
	WHERE (Customers.FirstName = 'Tina' AND
	Customers.LastName = 'Smith')

--Report all revenue generated by Iphones
SELECT ProductId, SUM(Price), FROM Orders INNER JOIN Products
	ON Orders.ProductId = Products.Id GROUP BY Products.Id
	WHERE Products.Name = 'IPhone'

GO
UPDATE Products SET Price = '250' WHERE Name = 'IPhone'